title: Your awesome title
logo: Awesome Logo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# --------------------------------------------------------
# SITE CONFIG
# --------------------------------------------------------

# Navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

#Footer Content
footer:  © your-name












# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
